### PR TITLE
Spring Cleaning

### PR DESCRIPTION
**Pull request by entrpntr**
Builds on top of the changes in #19, #21, #22, #23, #24, #25, #26, #27, and #29.

This PR mostly just contains cleanup work to match the folder structure and file names in pokecrystal, and also finish going through previously existing code to match current pokecrystal style to the extent possible.

May add follow-on commits in the next couple of days if there are any glaring issues, but will look to get all the changes up to and including this PR into the master branch by this weekend.

### CODE REVIEW

**Comment by dannye** [comment]
Do files like gfx/battle/balls.2bpp need to be committed?

**Comment by entrpntr** [comment]
I don't have a great gfx understanding, so pics that match the binaries in the ROM were what I've been committing for now. The current Makefile builds the pngs from those files, which was a relic from the one currently in master. I was going to look at implementing the reverse process that the other repos use before it was fully disassembled, if someone else doesn't do so before me. But for now, I've just been committing the binaries so it builds the correct ROM (I've also committed pngs so there is something viewable, and since they're going to be used eventually).

Now that I look though, the Makefile in master did have a target for making the binaries from the pngs (with gfx.py). There were only a handful of 1bpp and 2bpp targets (16 to be exact) that were built in current master from pngs, but I guess it's a bit of a regression that I no longer have it doing so. I could look again sometime soon; would be good for making sure the pngs I've committed actually can create the proper binaries.

**Comment by dannye** [comment]
I think having both the pngs and the bpps for now is fine, but eventually the intermediate bpps should be removed. Doesn't have to be done now for sure.

I skimmed the first 3000 files (GitHub won't show the diff of all 5000 lol) and everything besides the bpps looks great.

Running the build locally succeeds fine, but running `make clean` deletes a bunch of pngs.

**Comment by entrpntr** [comment]
Pushed a commit to remove deleting pngs since that's raised some eyebrows before (and added one other thing in naming_screen.asm I had forgotten about). I'll definitely look at the png -> bpp stuff when I get a chance to get rid of the redundancy.

**Comment by dannye** [comment]
Awesome stuff, thanks!

**Pull request merged**
