### PR TITLE
Document oversight with invalid mail handling + fix

### PR DESCRIPTION
**Pull request by CasualPokePlayer**
See https://github.com/pret/pokecrystal/pull/747

### CODE REVIEW

**Comment by Rangi42** [comment]
I don't think this is actually a bug. `$ff` is not a valid item ID in any context, since it's the standard array terminator. So in a loop scanning an array for a value, it doesn't matter what order the two checks for the desired value and the terminator happen. This is basically "if you hack in an invalid mail item ID, it can misbehave or crash in some circumstances", which also applies to owning a Pokémon #000 or #255, using move #0, etc.

**Comment by CasualPokePlayer** [comment]
The thing is, jr z, .invalid is only reached if the mail ID is well, invalid in the first place. The check seems to be intended to prevent some invalid mail type (possibly the result from save corruption/dead battery shenanigans/I guess also, you hack it in) from just crashing/hanging the game. This check is not reached for the case the mail type was corrupted to FF, in which case the game will treat it as a valid mail type and jump to $21C5, although for Gold/Silver this is largely harmless since it just returns right away (although Crystal usually ends up crashing from it), which I still consider a bug since the error handling ends up failing since it's done after the pointer check (doing the error check first will prevent this from happening). Although, I suppose that is still fair, there really isn't a way to trigger this without some sort of corruption in the first place.

**Comment by Rangi42** [comment]
It's not meant as a check for Mail with the invalid type -1. The game assumes that will never happen, because it won't. The check is meant for the `db -1` that terminates `MailGFXPointers`.

**Comment by CasualPokePlayer** [comment]
I didn't mean that. I mean it's meant as a general check for invalid error types. The terminator is only reached if the game finds no matches for the mail type it's trying to load (hence the label .invalid). Again, this only happens if the mail type is invalid, ie it was corrupted or hacked. If the mail type is valid, this terminator is never used. This general error check just fails for 1 case, the case mail was corrupted to FF, since the check is after the pointer check.

**Pull request closed without merging**
