### PR TITLE
Home and HRAM cleanup

### PR DESCRIPTION
**Pull request by libjet**
Mainly updated the beginning of home.asm to be closer to Pokecrystal, and also updated hram.asm to use labels (Changed in Pokecrystal about 2 years ago)

### CODE REVIEW

**Comment by mid-kid** [comment]
Quick heads-up, I'll be making some changes to home/ soon-ish. Not a lot, but the obvious stuff like:
`home/copy.asm` → `home/gfx.asm`
and
`home/copy2.asm` → `home/copy.asm`
and moving the last few things out of `home.asm` proper.

I'll link the appropriate PR here once it's done.

**Comment by libjet** [comment]
Okay, I'm not quite finished with home.asm yet, but I guess I just wanted to get this PR out there, so I'll update it when you're done.

**Comment by mid-kid** [comment]
Relevant changes in pokecrystal: https://github.com/pret/pokecrystal/pull/687

**Comment by entrpntr** [comment]
I finally took a look at what hadn't been cleaned up in home, and cleanup should now be mostly complete as of the changes in #25.

**Pull request merged**
